/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    // Identity pool id was replaced with: "AWS_IDENTITY_POOL_ID" for privacy.
    "aws_cognito_identity_pool_id": "AWS_IDENTITY_POOL_ID",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DvTplVLLl",
    // Web client id was replaced with: "AWS_CLIENT_ID" for privacy.
    "aws_user_pools_web_client_id": "AWS_CLIENT_ID",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
